# Generated by Django 3.0.6 on 2020-06-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comments_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_id',
        ),
    ]
