# Generated by Django 3.0.6 on 2020-06-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_comments_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_slug',
            field=models.CharField(default='something', max_length=255),
            preserve_default=False,
        ),
    ]
