# Generated by Django 3.0.6 on 2020-06-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comments_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
